from pathlib import Path
path = Path('src/app/components/layout/Sidebar.tsx')
text = path.read_text(encoding='utf-8')
old1 = "  const [caissesOpen, setCaissesOpen] = useState(() => caissesActive(activeView));\n  const [tarecOpen, setTarecOpen] = useState(() => activeView === 'saisie-anomalies');\n"
new1 = "  const [tarecOpen, setTarecOpen] = useState(() => activeView === 'saisie-anomalies');\n"
old2 = "        {sidebarOpen && (\n          <div className={`${isCaissesActive ? 'bg-[#e8eef5]' : 'bg-[#eef2f6]'}`}>\n            <div\n              className={`flex items-center gap-2 py-2 pl-12 pr-3 text-[12.5px] cursor-pointer transition-colors ${\n                isCaissesActive\n                  ? 'text-[#1a5fa8] font-semibold'\n                  : 'text-[#5c6b82] hover:text-[#1a5fa8]'\n              }`}\n              onClick={() => onSetView('saisie')}\n              data-testid=\"subnav-saisie\"\n            >\n              <span className=\"w-1.5 h-1.5 rounded-full bg-[#1a5fa8] shrink-0\" />\n              Saisie / Modification\n            </div>\n          </div>\n        )}"
new2 = "        {sidebarOpen && (\n          <div className={`${isCaissesActive ? 'bg-[#e8eef5]' : 'bg-[#eef2f6]'}`}>\n            {role === 'CCO' ? (\n              <div\n                className={`flex items-center gap-2 py-2 pl-12 pr-3 text-[12.5px] cursor-pointer transition-colors ${\n                  isCaissesActive\n                    ? 'text-[#1a5fa8] font-semibold'\n                    : 'text-[#5c6b82] hover:text-[#1a5fa8]'\n                }`}\n                onClick={() => onSetView('saisie')}\n                data-testid=\"subnav-saisie\"\n              >\n                <span className=\"w-1.5 h-1.5 rounded-full bg-[#1a5fa8] shrink-0\" />\n                Saisie / Modification\n              </div>\n            ) : (\n              supervisorItems.map(item => {\n                const active = activeView === item.view;\n                return (\n                  <div\n                    key={item.view}\n                    className={`flex items-center gap-2 py-2 pl-12 pr-3 text-[12.5px] cursor-pointer transition-colors ${\n                      active ? 'text-[#1a5fa8] font-semibold' : 'text-[#5c6b82] hover:text-[#1a5fa8]'\n                    }`}\n                    onClick={() => onSetView(item.view)}\n                  >\n                    <span className=\"w-1.5 h-1.5 rounded-full bg-[#1a5fa8] shrink-0\" />\n                    {item.label}\n                  </div>\n                );\n              })\n            )}\n          </div>\n        )}"
if old1 not in text or old2 not in text:
    print('Old block not found')
    raise SystemExit(1)
path.write_text(text.replace(old1, new1).replace(old2, new2), encoding='utf-8')
print('updated')
